apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: solidarity-connection
  labels:
    app: solidarity-connection
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  NewRelic__OtlpEndpoint: "https://otlp.nr-data.net:4317"
  NewRelic__Protocol: "grpc"