apiVersion: v1
kind: Secret
metadata:
  name: fiap-users-secret
  namespace: solidarity-connection
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "<connection_string>"
  JwtSettings__SecretKey: "<secret_key>"
  JwtSettings__Issuer: "solidarityconnection-core-api"
  JwtSettings__Audience: "solidarityconnection"
